### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by JunxiFeng** [Legana/AMP_pub#21]
Hello,

Which dataset is the training data for the precursor model?

Thanks!

**Comment by Legana** [comment]
Hi JunxiFeng. For the current version of ampir the training dataset for the ampir precursor model is the file `v1.1_featuresTrain_precursor_imbal.rds` within the ampir_v1.1.0 folder inside the data_amp_pub folder available on Cloudstor (see the README for the link).

**Comment by JunxiFeng** [comment]
Hi Legana,

What about the sequences that are used? There's only seq name in the rds data. 

Thanks again!

**Comment by JunxiFeng** [comment]
I think I found them! Thank you so much!
